[tools]
bun = "latest"
node = "24"
npm = "latest"
github-cli = "latest"
gh = "latest"
gradle = "latest"
maven = "latest"
android-sdk = "latest"
dotnet-core = "latest"
dotnet = "latest"
copilot-cli = "latest"
ruby = "latest"
cocoapods = "latest"
gemini-cli = "latest"
cmake = "latest"
nsc = "latest"
