[tools]
"github:composer/composer" = "latest"
jsonschema = "latest"
python = "3.12"
"ubi:composer/composer" = "latest"
bun = "latest"
node = "latest"
ruby = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
"aqua:aws/aws-cli" = "latest"

[env]
mise = { file = ".env" }


[deps]
npm = { auto = true }
bun = { auto = true }
bundler = { auto = true }

[settings]
always_keep_download = true
auto_env = true
github = {}
github_attestations = true
ruby = {}
swift = {}
enable_tools = []
node = {}
java = {}
npm = {}
oci = {}
yes = true
terminal_progress = true
