sonar.projectKey=AiMarketingtool-pro-fbaf2fad
sonar.projectName=AiMarketingtool-pro-fbaf2fad
sonar.sources=android/app/src/main/java,src
sonar.sourceEncoding=UTF-8
sonar.java.binaries=android/app/build/intermediates/javac/debug/classes
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
