import wmill
import json

# ── Router: dispatches to correct engine based on toolSlug ─────────────────
# This is the single entry point. Frontend can call this instead of
# individual engines. Routes by toolSlug → engineType → engine script.

TOOL_ROUTING = {
    # Complete map: every one of the 314 tool slugs is routed explicitly.
    #
    # Before this, only 36 slugs were listed and main() did
    #     engine_type = TOOL_ROUTING.get(toolSlug, "creative")
    # so the other ~278 tools silently ran through engine-creative -- the
    # copywriting engine. A budget optimiser, a quality-score checker and an
    # audit tool were all being executed as copywriting jobs, which is why
    # their output read as generic marketing prose.
    #
    # The original 36 curated entries are preserved exactly; the rest are
    # assigned from each tool's own badge in src/data/tools.js:
    #   creative   = produces copy / content
    #   automation = creates or manages campaigns and workflows
    #   insight    = analyses, audits, scores, reports
    #
    # Distribution: 137 creative, 107 automation, 70 insight.
    "academic-writer": "creative",
    "ad-audit-tool": "insight",
    "ad-budget-allocator": "creative",
    "ad-copy-analyzer": "automation",
    "ad-copy-insights": "automation",
    "ad-copy-sentiment-analyzer": "automation",
    "ad-fatigue-detector": "automation",
    "ad-group-audit": "insight",
    "ad-intelligence-software": "insight",
    "ad-position-tool": "automation",
    "ad-ranking-tool": "automation",
    "ad-set-storyline": "automation",
    "ad-testing": "automation",
    "ad-testing-tools": "automation",
    "ads-launcher": "automation",
    "ads-rotation-agent": "automation",
    "advanced-ad-analyzer": "automation",
    "advantage-plus-campaign-builder": "creative",
    "adwords-keyword-tool": "automation",
    "affiliate-marketing-copy": "creative",
    "ai-ad-management-tools": "automation",
    "ai-ads-generator": "automation",
    "ai-advertising-suite": "automation",
    "ai-campaign-manager": "automation",
    "ai-creative-director": "creative",
    "ai-media-buyer": "automation",
    "ai-paid-social-manager": "automation",
    "ai-performance-marketer": "automation",
    "ai-task-prioritizer": "automation",
    "amazon-ppc-optimizer": "creative",
    "api-documentation-generator": "insight",
    "article-generator": "creative",
    "article-rewriter": "creative",
    "article-summarizer": "creative",
    "attribution-window-optimizer": "creative",
    "audience-optimization-tool": "automation",
    "auditing": "insight",
    "auto-scaling-budget-tool": "insight",
    "automated-ad-launch-tool": "automation",
    "automation": "automation",
    "autonomous-marketing-manager": "automation",
    "backlink-outreach-email-generator": "insight",
    "bid-optimization-engine": "automation",
    "bid-suggestions-tool": "insight",
    "blog-conclusion-writer": "creative",
    "blog-intro-writer": "creative",
    "blog-outline-writer": "creative",
    "blog-post-ideas": "creative",
    "blog-writer": "creative",
    "brand-identity-builder": "creative",
    "brand-safety-monitor": "insight",
    "brand-voice-generator": "creative",
    "budget-management": "insight",
    "budget-manager": "automation",
    "budget-performance-analyzer": "insight",
    "campaign-ab-test-manager": "automation",
    "campaign-audit-tool": "insight",
    "campaign-auto-optimizer": "automation",
    "campaign-budget-allocator": "automation",
    "campaign-cloner-pro": "automation",
    "campaign-compliance-checker": "insight",
    "campaign-health-monitor": "automation",
    "campaign-optimization-engine": "automation",
    "campaign-performance-predictor": "automation",
    "campaign-scaling-assistant": "automation",
    "campaign-template-library": "automation",
    "campaign-tools-suite": "automation",
    "caption-creator": "creative",
    "cart-abandonment-analyzer": "creative",
    "cart-recovery-ads": "creative",
    "case-study-writer": "creative",
    "client-reporting-portal": "insight",
    "code-comments-generator": "insight",
    "cold-outreach-email": "creative",
    "comparison-chart-creator": "creative",
    "competitive-benchmarking-ai": "insight",
    "competitor-analysis-tool": "insight",
    "content-gap-finder": "insight",
    "content-rewriter": "creative",
    "conversion-path-analyzer": "insight",
    "conversion-rate-optimizer": "creative",
    "copy-generator": "creative",
    "creative-fatigue-detector": "creative",
    "creative-fatigue-predictor": "creative",
    "creative-intelligence-platform": "creative",
    "creative-optimization-ai": "creative",
    "creative-performance-analyzer": "creative",
    "creative-refresh-agent": "creative",
    "cross-sell-ad-generator": "creative",
    "cross-sell-upsell-flow-builder": "creative",
    "cta-writer": "creative",
    "ctr-optimizer": "automation",
    "ctr-predictor": "automation",
    "customer-acquisition-cost-optimizer": "creative",
    "customer-journey-intelligence": "insight",
    "customer-lifetime-value-calculator": "creative",
    "customer-winback-flow-creator": "creative",
    "data-studio-reporting": "insight",
    "dayparting-optimizer": "automation",
    "device-optimization": "automation",
    "dki-tool": "automation",
    "dynamic-pricing-optimizer": "creative",
    "dynamic-product-ads": "creative",
    "ecommerce-ab-test-planner": "creative",
    "ecommerce-ad-platform": "creative",
    "ecommerce-chatbot-builder": "creative",
    "ecommerce-growth-roadmap-generator": "creative",
    "ecommerce-kpi-dashboard": "creative",
    "ecommerce-reporting-automator": "creative",
    "ecommerce-workflow-automator": "creative",
    "email-writer": "creative",
    "engagement-calculator": "insight",
    "exam-prep-content": "creative",
    "explainer-generator": "insight",
    "facebook-ads-manager": "automation",
    "facebook-ads-orchestrator": "automation",
    "facebook-ads-performance-grader": "insight",
    "facebook-marketing-suite": "automation",
    "facebook-performance-dashboard": "automation",
    "faq-generator": "creative",
    "faq-schema-writer": "insight",
    "free-keyword-tools": "insight",
    "free-ppc-tools": "insight",
    "free-tool-comparisons": "automation",
    "geo-targeting-optimizer": "automation",
    "google-ads-budget-calculator": "automation",
    "google-ads-editor-alternative": "automation",
    "google-ads-manager": "automation",
    "google-ads-performance-grader": "insight",
    "google-ads-quality-score": "insight",
    "google-analytics-grader": "insight",
    "google-shopping-optimizer": "creative",
    "google-trends-tool": "insight",
    "gross-margin-analyzer": "creative",
    "hashtag-generator": "creative",
    "image-resizer": "creative",
    "instagram-ad-creative-generator": "creative",
    "instagram-ai-automation": "creative",
    "instagram-bio-optimizer": "creative",
    "instagram-caption-generator": "creative",
    "instagram-carousel-designer": "creative",
    "instagram-competitor-analyzer": "creative",
    "instagram-content-scheduler": "creative",
    "instagram-engagement-analyzer": "creative",
    "instagram-growth-strategy": "creative",
    "instagram-hashtag-strategy": "creative",
    "instagram-influencer-finder": "creative",
    "instagram-management-tools": "creative",
    "instagram-marketing-platform": "creative",
    "instagram-reels-optimizer": "creative",
    "instagram-shopping-ads": "creative",
    "instagram-story-ads-manager": "creative",
    "intelligent-automation-platform": "automation",
    "internal-linking-suggestions": "insight",
    "inventory-based-ad-manager": "creative",
    "keyword-audit-tool": "insight",
    "keyword-cluster-generator": "insight",
    "keyword-grouping-tool": "automation",
    "keyword-intent-analyzer": "automation",
    "keyword-intent-detector": "insight",
    "keyword-research-tool": "insight",
    "landing-page-audit": "insight",
    "lead-magnet-creator": "automation",
    "linkedin-ad-copy-generator": "creative",
    "long-tail-keyword-generator": "insight",
    "loyalty-vip-rewards-designer": "creative",
    "market-research-summary": "creative",
    "marketing-ai-agents-hub": "automation",
    "marketing-asset-library": "creative",
    "marketing-budget-planner": "insight",
    "marketing-calendar": "creative",
    "marketing-copy-generator": "creative",
    "marketing-efficiency-ratio-tracker": "creative",
    "marketing-efficiency-software": "creative",
    "marketing-kpi-dashboard": "insight",
    "marketing-proposal-generator": "creative",
    "marketing-software-hub": "creative",
    "marketing-team-collaboration": "creative",
    "meta-ad-cost-calculator": "automation",
    "meta-ad-launcher": "automation",
    "meta-ads-dashboard": "automation",
    "meta-ads-manager-2": "automation",
    "meta-ai-comment-responder": "automation",
    "meta-ai-copywriter": "creative",
    "meta-ai-marketer": "automation",
    "meta-attribution-tool": "automation",
    "meta-audience-builder": "automation",
    "meta-audience-launcher": "automation",
    "meta-audience-studio": "automation",
    "meta-automated-reporting": "automation",
    "meta-automation-tactics": "automation",
    "meta-autonomous-budget-optimizer": "automation",
    "meta-budget-optimizer": "automation",
    "meta-campaign-analyzer": "automation",
    "meta-cloud-tracking": "automation",
    "meta-comment-manager": "automation",
    "meta-conversion-tracker": "automation",
    "meta-conversions-api": "automation",
    "meta-creative-insights": "automation",
    "meta-creative-studio": "automation",
    "meta-custom-audiences": "automation",
    "meta-custom-automation": "automation",
    "meta-description-generator": "insight",
    "meta-full-automation-suite": "automation",
    "meta-hidden-insights": "automation",
    "meta-placement-optimizer": "automation",
    "meta-smart-filter": "automation",
    "meta-target-audience-finder": "automation",
    "meta-white-label": "automation",
    "microsoft-ads-grader": "insight",
    "milestone-email-automator": "automation",
    "monitoring": "automation",
    "multi-channel-attribution": "insight",
    "multi-platform-campaign-hub": "automation",
    "negative-keyword-audit": "insight",
    "negative-keywords-tool": "automation",
    "omnichannel-campaign-orchestrator": "creative",
    "on-page-seo-checker": "insight",
    "optimization-software-suite": "creative",
    "paragraph-expander": "creative",
    "paragraph-improver": "creative",
    "paragraph-rewriter": "creative",
    "paragraph-shortener": "creative",
    "paragraph-simplifier": "creative",
    "performance-auto-alerts": "insight",
    "performance-forecasting": "insight",
    "performance-intelligence-dashboard": "insight",
    "performance-max": "automation",
    "performance-max-campaign-manager": "creative",
    "pinterest-ad-generator": "creative",
    "placement-audit": "insight",
    "placement-optimization": "automation",
    "platform-expansion-planner": "creative",
    "podcast-script-writer": "creative",
    "post-purchase-follow-up-builder": "creative",
    "post-scheduler": "automation",
    "ppc-ad-management-tools": "automation",
    "ppc-audit-analysis-tools": "insight",
    "ppc-audits-rule-engine": "automation",
    "ppc-bid-management-tools": "insight",
    "ppc-bidding-tools": "insight",
    "ppc-budget-tool": "insight",
    "ppc-campaign-builder": "automation",
    "ppc-keyword-analysis-tool": "automation",
    "ppc-optimization-tools": "automation",
    "ppc-performance-boost": "automation",
    "ppc-performance-monitoring-tools": "insight",
    "ppc-quality-score": "insight",
    "ppc-reporting-solution": "insight",
    "ppc-reporting-tools": "insight",
    "ppc-search-term-analysis": "automation",
    "predictive-inventory-manager": "creative",
    "press-release-generator": "creative",
    "product-description-writer": "creative",
    "product-feed-optimizer": "creative",
    "product-launch-email-sequence": "creative",
    "product-performance-tracker": "creative",
    "product-recommendation-engine": "creative",
    "quality-score-audit": "insight",
    "quality-score-checker": "insight",
    "real-time-meta-optimizer": "automation",
    "replenishment-reminder-engine": "creative",
    "reporting-tools": "insight",
    "retargeting-funnel-builder": "automation",
    "roas-analyzer": "creative",
    "roas-prediction-platform": "insight",
    "roi-calculator": "insight",
    "roi-intelligence-platform": "insight",
    "rule-based-campaign-manager": "automation",
    "sales-page-copy-writer": "creative",
    "schema-generator": "insight",
    "scientific-ad-testing": "automation",
    "search-term-audit": "insight",
    "seasonal-ecommerce-planner": "creative",
    "sentence-expander": "creative",
    "sentence-rewriter": "creative",
    "sentence-shortener": "creative",
    "sentence-simplifier": "creative",
    "seo-audit-tool": "insight",
    "seo-title-generator": "creative",
    "serp-analyzer": "insight",
    "shopify-app-stack-advisor": "creative",
    "shopify-campaign-manager": "automation",
    "shopify-email-flow-builder": "creative",
    "shopify-marketing-tools": "creative",
    "shopify-product-page-enhancer": "creative",
    "shopify-seo-optimizer": "creative",
    "shopify-store-audit": "creative",
    "shopify-theme-conversion-optimizer": "creative",
    "shopify-trust-badge-optimizer": "creative",
    "shopify-upsell-strategy-generator": "creative",
    "shopping-campaign-intelligence": "automation",
    "smart-scheduling-engine": "automation",
    "social-analytics-dashboard": "creative",
    "social-commerce-ad-launcher": "creative",
    "social-hashtag-generator": "creative",
    "social-media-post-generator": "creative",
    "study-notes-generator": "creative",
    "technical-explanation-writer": "insight",
    "testimonial-generator": "creative",
    "tiktok-ad-creator": "creative",
    "tiktok-ecommerce-ad-creator": "creative",
    "twitter-thread-generator": "creative",
    "unified-analytics-platform": "insight",
    "visual-performance-optimizer": "creative",
    "voice-search-product-optimizer": "creative",
    "webinar-script-writer": "creative",
    "website-grader": "insight",
    "welcome-series-generator": "creative",
    "whitepaper-generator": "creative",
    "workflow-automation-builder": "automation",
    "youtube-ad-script-writer": "creative",
    "youtube-description-generator": "creative",
    "youtube-title-generator": "creative",}


ENGINE_SCRIPTS = {
    "creative": "f/tools/engine-creative",
    "automation": "f/tools/engine-automation",
    "insight": "f/tools/engine-insight",
}


def main(
    toolSlug: str = "",
    toolName: str = "",
    toolDescription: str = "",
    toolBadge: str = "",
    input: str = "",
    additionalInputs: dict = {},
    userId: str = "",
    appwriteJwt: str = ""
):
    """Router — routes toolSlug to correct engine script."""
    engine_type = TOOL_ROUTING.get(toolSlug, "creative")
    script = ENGINE_SCRIPTS.get(engine_type, "f/tools/engine-creative")

    return wmill.run_script(script, args={
        "toolSlug": toolSlug,
        "toolName": toolName,
        "toolDescription": toolDescription or "",
        "toolBadge": toolBadge or "",
        "input": input,
        "additionalInputs": additionalInputs or {},
        "userId": userId,
        "appwriteJwt": appwriteJwt,
    })
