// Auto-generated tool icon mapping — cleaned and deduplicated
// Icons from /Users/loken/Pictures/New Folder icon packs
const ToolIconImages: Record<string, any> = {
  '01-ai-brain-chip': require('../assets/images/tool-icons-v2/01 ai brain chip.webp'),
  '01-ai-robot': require('../assets/images/tool-icons-v2/01 ai robot.webp'),
  '01facebook': require('../assets/images/tool-icons-v2/01_Facebook.webp'),
  '02-ai-brain-chip': require('../assets/images/tool-icons-v2/02 ai brain chip.webp'),
  '02-ai-robot': require('../assets/images/tool-icons-v2/02 ai robot.webp'),
  '02instagram': require('../assets/images/tool-icons-v2/02_Instagram.webp'),
  '03x': require('../assets/images/tool-icons-v2/03_X.webp'),
  '04linkedin': require('../assets/images/tool-icons-v2/04_LinkedIn.webp'),
  '05youtube': require('../assets/images/tool-icons-v2/05_Youtube.webp'),
  '06whatsapp': require('../assets/images/tool-icons-v2/06_WhatsApp.webp'),
  '07reddit': require('../assets/images/tool-icons-v2/07_Reddit.webp'),
  '08tumblr': require('../assets/images/tool-icons-v2/08_Tumblr.webp'),
  '09snapchat': require('../assets/images/tool-icons-v2/09_Snapchat.webp'),
  '1-a': require('../assets/images/tool-icons-v2/1 a.webp'),
  '1-cyber-security': require('../assets/images/tool-icons-v2/1 cyber security.webp'),
  '1-cyberpunk': require('../assets/images/tool-icons-v2/1 Cyberpunk.webp'),
  '1-data-analytic': require('../assets/images/tool-icons-v2/1 - Data Analytic.webp'),
  '1-laptop': require('../assets/images/tool-icons-v2/1. Laptop.webp'),
  '1-nft': require('../assets/images/tool-icons-v2/1--nft.webp'),
  '1-online-store': require('../assets/images/tool-icons-v2/1-online-store.webp'),
  '1-seo': require('../assets/images/tool-icons-v2/1-seo.webp'),
  '1-tas-b': require('../assets/images/tool-icons-v2/1. Tas-b.webp'),
  '1-technology': require('../assets/images/tool-icons-v2/1-technology.webp'),
  '1-web-report': require('../assets/images/tool-icons-v2/1. Web Report.webp'),
  '10': require('../assets/images/tool-icons-v2/10.webp'),
  '10-a': require('../assets/images/tool-icons-v2/10 a.webp'),
  '10-copywriter': require('../assets/images/tool-icons-v2/10-copywriter.webp'),
  '10-cyborg': require('../assets/images/tool-icons-v2/10 Cyborg.webp'),
  '10-digital-artist-female': require('../assets/images/tool-icons-v2/10--digital-artist-female.webp'),
  '10-link-building': require('../assets/images/tool-icons-v2/10-link-building.webp'),
  '10-marketing-target': require('../assets/images/tool-icons-v2/10. Marketing Target.webp'),
  '10-mouse': require('../assets/images/tool-icons-v2/10. Mouse.webp'),
  '10-review': require('../assets/images/tool-icons-v2/10. Review.webp'),
  '10-robot': require('../assets/images/tool-icons-v2/10-robot.webp'),
  '10-seo-filter': require('../assets/images/tool-icons-v2/10 - SEO Filter.webp'),
  '10-zero-trust': require('../assets/images/tool-icons-v2/10 Zero Trust.webp'),
  '10pinterest': require('../assets/images/tool-icons-v2/10_Pinterest.webp'),
  '11': require('../assets/images/tool-icons-v2/11.webp'),
  '11-a': require('../assets/images/tool-icons-v2/11 a.webp'),
  '11-analytics': require('../assets/images/tool-icons-v2/11-analytics.webp'),
  '11-artificial-intelliegence': require('../assets/images/tool-icons-v2/11-artificial-intelliegence.webp'),
  '11-content-creator': require('../assets/images/tool-icons-v2/11-content-creator.webp'),
  '11-copywriting': require('../assets/images/tool-icons-v2/11 - Copywriting.webp'),
  '11-gift-b': require('../assets/images/tool-icons-v2/11. Gift-b.webp'),
  '11-global-market': require('../assets/images/tool-icons-v2/11. Global Market.webp'),
  '11-metaverse': require('../assets/images/tool-icons-v2/11--metaverse.webp'),
  '11-monitor': require('../assets/images/tool-icons-v2/11. Monitor.webp'),
  '11-robot': require('../assets/images/tool-icons-v2/11 Robot.webp'),
  '11-virus': require('../assets/images/tool-icons-v2/11 Virus.webp'),
  '11tiktok': require('../assets/images/tool-icons-v2/11_TikTok.webp'),
  '12': require('../assets/images/tool-icons-v2/12.webp'),
  '12-authority': require('../assets/images/tool-icons-v2/12-authority.webp'),
  '12-autonomous-vehicle': require('../assets/images/tool-icons-v2/12-autonomous-vehicle.webp'),
  '12-cctv-camera': require('../assets/images/tool-icons-v2/12 CCTV Camera.webp'),
  '12-cs': require('../assets/images/tool-icons-v2/12. CS.webp'),
  '12-digital-wallet': require('../assets/images/tool-icons-v2/12--digital-wallet.webp'),
  '12-internet-search': require('../assets/images/tool-icons-v2/12 - Internet Search.webp'),
  '12-malware': require('../assets/images/tool-icons-v2/12 Malware.webp'),
  '12-mobile-ads': require('../assets/images/tool-icons-v2/12. Mobile Ads.webp'),
  '12-podcaster': require('../assets/images/tool-icons-v2/12-podcaster.webp'),
  '12-printer': require('../assets/images/tool-icons-v2/12. Printer.webp'),
  '12skype': require('../assets/images/tool-icons-v2/12_Skype.webp'),
  '13': require('../assets/images/tool-icons-v2/13.webp'),
  '13-affiliate-marketer': require('../assets/images/tool-icons-v2/13-affiliate-marketer.webp'),
  '13-crawling': require('../assets/images/tool-icons-v2/13-crawling.webp'),
  '13-customer-engagement': require('../assets/images/tool-icons-v2/13. Customer Engagement.webp'),
  '13-drugs': require('../assets/images/tool-icons-v2/13 Drugs.webp'),
  '13-guarantee-b': require('../assets/images/tool-icons-v2/13. Guarantee-b.webp'),
  '13-ransomware': require('../assets/images/tool-icons-v2/13 Ransomware.webp'),
  '13-smart-contract': require('../assets/images/tool-icons-v2/13--smart-contract.webp'),
  '13-smart-home': require('../assets/images/tool-icons-v2/13-smart-home.webp'),
  '13-social-media-engagement': require('../assets/images/tool-icons-v2/13 - Social Media Engagement.webp'),
  '13-speaker': require('../assets/images/tool-icons-v2/13. Speaker.webp'),
  '13-usb': require('../assets/images/tool-icons-v2/13. USB.webp'),
  '13vimeo': require('../assets/images/tool-icons-v2/13_Vimeo.webp'),
  '14': require('../assets/images/tool-icons-v2/14.webp'),
  '14-a': require('../assets/images/tool-icons-v2/14 a.webp'),
  '14-binary-code': require('../assets/images/tool-icons-v2/14 Binary Code.webp'),
  '14-browse': require('../assets/images/tool-icons-v2/14. Browse.webp'),
  '14-cd': require('../assets/images/tool-icons-v2/14. CD.webp'),
  '14-customer-network': require('../assets/images/tool-icons-v2/14. Customer Network.webp'),
  '14-ethereum': require('../assets/images/tool-icons-v2/14-ethereum.webp'),
  '14-feedback': require('../assets/images/tool-icons-v2/14 - Feedback.webp'),
  '14-indexing': require('../assets/images/tool-icons-v2/14-indexing.webp'),
  '14-phishing': require('../assets/images/tool-icons-v2/14 Phishing.webp'),
  '14-renewable-energy': require('../assets/images/tool-icons-v2/14-renewable-energy.webp'),
  '14-video-conference': require('../assets/images/tool-icons-v2/14-video-conference.webp'),
  '14behance': require('../assets/images/tool-icons-v2/14_Behance.webp'),
  '15': require('../assets/images/tool-icons-v2/15.webp'),
  '15-cloud-storage': require('../assets/images/tool-icons-v2/15. Cloud Storage.webp'),
  '15-content-marketing': require('../assets/images/tool-icons-v2/15 - Content Marketing.webp'),
  '15-graphic-designer': require('../assets/images/tool-icons-v2/15-graphic-designer.webp'),
  '15-hacker': require('../assets/images/tool-icons-v2/15 Hacker.webp'),
  '15-lead-magnet': require('../assets/images/tool-icons-v2/15. Lead Magnet.webp'),
  '15-man-in-the-middle-mitm': require('../assets/images/tool-icons-v2/15 Man in the middle (MITM).webp'),
  '15-metadata': require('../assets/images/tool-icons-v2/15--metadata.webp'),
  '15-sitemap': require('../assets/images/tool-icons-v2/15-sitemap.webp'),
  '15-television': require('../assets/images/tool-icons-v2/15-television.webp'),
  '15-web-shop-b': require('../assets/images/tool-icons-v2/15. Web Shop-b.webp'),
  '15dribbble': require('../assets/images/tool-icons-v2/15_Dribbble.webp'),
  '16': require('../assets/images/tool-icons-v2/16.webp'),
  '16-distributed-denial-of-service-ddos': require('../assets/images/tool-icons-v2/16 Distributed Denial of Service (DDos).webp'),
  '16-genetic-engineering': require('../assets/images/tool-icons-v2/16-genetic-engineering.webp'),
  '16-keyword-research': require('../assets/images/tool-icons-v2/16 - Keyword Research.webp'),
  '16-marketing-bot2': require('../assets/images/tool-icons-v2/16. Marketing Bot2.webp'),
  '16-mobile-shop': require('../assets/images/tool-icons-v2/16. Mobile Shop.webp'),
  '16-network': require('../assets/images/tool-icons-v2/16. Network.webp'),
  '16-on-chain': require('../assets/images/tool-icons-v2/16--on-chain.webp'),
  '16-vaporwave': require('../assets/images/tool-icons-v2/16 Vaporwave.webp'),
  '16-white-hat': require('../assets/images/tool-icons-v2/16-white-hat.webp'),
  '16-worldwide-shipping': require('../assets/images/tool-icons-v2/16-worldwide-shipping.webp'),
  '16flickr': require('../assets/images/tool-icons-v2/16_Flickr.webp'),
  '17': require('../assets/images/tool-icons-v2/17.webp'),
  '17-a': require('../assets/images/tool-icons-v2/17 a.webp'),
  '17-account-takeover-ato': require('../assets/images/tool-icons-v2/17 Account Takeover (ATO).webp'),
  '17-backlink': require('../assets/images/tool-icons-v2/17 - Backlink.webp'),
  '17-black-hat': require('../assets/images/tool-icons-v2/17-black-hat.webp'),
  '17-buyer': require('../assets/images/tool-icons-v2/17-buyer.webp'),
  '17-clonning': require('../assets/images/tool-icons-v2/17-clonning.webp'),
  '17-eye-scanner': require('../assets/images/tool-icons-v2/17 Eye Scanner.webp'),
  '17-funelling': require('../assets/images/tool-icons-v2/17. Funelling.webp'),
  '17-off-chain': require('../assets/images/tool-icons-v2/17-off-chain.webp'),
  '17-server': require('../assets/images/tool-icons-v2/17. Server.webp'),
  '17-warehouse-b': require('../assets/images/tool-icons-v2/17. Warehouse-b.webp'),
  '17google': require('../assets/images/tool-icons-v2/17_Google.webp'),
  '18': require('../assets/images/tool-icons-v2/18.webp'),
  '18-a': require('../assets/images/tool-icons-v2/18 a.webp'),
  '18-city': require('../assets/images/tool-icons-v2/18 City.webp'),
  '18-creative-person': require('../assets/images/tool-icons-v2/18-creative-person.webp'),
  '18-digital-medicine': require('../assets/images/tool-icons-v2/18-digital-medicine.webp'),
  '18-discounted-time-b': require('../assets/images/tool-icons-v2/18. Discounted Time-b.webp'),
  '18-firewall': require('../assets/images/tool-icons-v2/18. Firewall.webp'),
  '18-hacking': require('../assets/images/tool-icons-v2/18 Hacking.webp'),
  '18-landing-page': require('../assets/images/tool-icons-v2/18-landing-page.webp'),
  '18-market-analysis': require('../assets/images/tool-icons-v2/18 - Market Analysis.webp'),
  '18-marketing-plan': require('../assets/images/tool-icons-v2/18. Marketing Plan.webp'),
  '18-nft-collectables': require('../assets/images/tool-icons-v2/18--nft-collectables.webp'),
  '18b': require('../assets/images/tool-icons-v2/18b.webp'),
  '18soundcloud': require('../assets/images/tool-icons-v2/18_SoundCloud.webp'),
  '19': require('../assets/images/tool-icons-v2/19.webp'),
  '19-a': require('../assets/images/tool-icons-v2/19 a.webp'),
  '19-chat': require('../assets/images/tool-icons-v2/19. Chat.webp'),
  '19-insider-threat': require('../assets/images/tool-icons-v2/19 Insider Threat.webp'),
  '19-internet-of-things-iot': require('../assets/images/tool-icons-v2/19-internet-of-things-iot.webp'),
  '19-link-building': require('../assets/images/tool-icons-v2/19. Link Building.webp'),
  '19-marketing-strategy': require('../assets/images/tool-icons-v2/19-marketing-strategy.webp'),
  '19-mohawk-skull': require('../assets/images/tool-icons-v2/19 Mohawk Skull.webp'),
  '19-nft-marketplace': require('../assets/images/tool-icons-v2/19--nft-marketplace.webp'),
  '19-online-business': require('../assets/images/tool-icons-v2/19-online-business.webp'),
  '19-optimization': require('../assets/images/tool-icons-v2/19 - Optimization.webp'),
  '19-router': require('../assets/images/tool-icons-v2/19. Router.webp'),
  '19spotify': require('../assets/images/tool-icons-v2/19_Spotify.webp'),
  '2-a': require('../assets/images/tool-icons-v2/2 a.webp'),
  '2-cart': require('../assets/images/tool-icons-v2/2. Cart.webp'),
  '2-cia-triad': require('../assets/images/tool-icons-v2/2 CIA Triad.webp'),
  '2-crypto': require('../assets/images/tool-icons-v2/2--crypto.webp'),
  '2-email-campaign': require('../assets/images/tool-icons-v2/2. Email Campaign.webp'),
  '2-email-marketing': require('../assets/images/tool-icons-v2/2 - Email Marketing.webp'),
  '2-online-promotion': require('../assets/images/tool-icons-v2/2-online-promotion.webp'),
  '2-science': require('../assets/images/tool-icons-v2/2-science.webp'),
  '2-science-fiction': require('../assets/images/tool-icons-v2/2 Science Fiction.webp'),
  '2-sem': require('../assets/images/tool-icons-v2/2-sem.webp'),
  '2-smartphone': require('../assets/images/tool-icons-v2/2. Smartphone.webp'),
  '20': require('../assets/images/tool-icons-v2/20.webp'),
  '20-a': require('../assets/images/tool-icons-v2/20 a.webp'),
  '20-ab-testing': require('../assets/images/tool-icons-v2/20 - AB Testing.webp'),
  '20-data-breach': require('../assets/images/tool-icons-v2/20 Data Breach.webp'),
  '20-gps-b': require('../assets/images/tool-icons-v2/20. GPS-b.webp'),
  '20-loot-boxes': require('../assets/images/tool-icons-v2/20--loot-boxes.webp'),
  '20-megacorporation': require('../assets/images/tool-icons-v2/20 Megacorporation.webp'),
  '20-microchip': require('../assets/images/tool-icons-v2/20-microchip.webp'),
  '20-networking': require('../assets/images/tool-icons-v2/20-networking.webp'),
  '20-pay-per-click': require('../assets/images/tool-icons-v2/20. Pay Per Click.webp'),
  '20-satellite': require('../assets/images/tool-icons-v2/20. Satellite.webp'),
  '20-seo-team': require('../assets/images/tool-icons-v2/20-seo-team.webp'),
  '20b': require('../assets/images/tool-icons-v2/20b.webp'),
  '20vine': require('../assets/images/tool-icons-v2/20_Vine.webp'),
  '21': require('../assets/images/tool-icons-v2/21.webp'),
  '21-a': require('../assets/images/tool-icons-v2/21 a.webp'),
  '21-cyberspace': require('../assets/images/tool-icons-v2/21 Cyberspace.webp'),
  '21-internet': require('../assets/images/tool-icons-v2/21-internet.webp'),
  '21-landing-page': require('../assets/images/tool-icons-v2/21 - Landing Page.webp'),
  '21-marketing-team': require('../assets/images/tool-icons-v2/21-marketing-team.webp'),
  '21-nft-art': require('../assets/images/tool-icons-v2/21--nft-art.webp'),
  '21-virtual-private-network-vpn': require('../assets/images/tool-icons-v2/21 Virtual Private Network (VPN).webp'),
  '21discord': require('../assets/images/tool-icons-v2/21_Discord.webp'),
  '22': require('../assets/images/tool-icons-v2/22.webp'),
  '22-a': require('../assets/images/tool-icons-v2/22 a.webp'),
  '22-firewall': require('../assets/images/tool-icons-v2/22 Firewall.webp'),
  '22-high-tech': require('../assets/images/tool-icons-v2/22 High Tech.webp'),
  '22-mobile-optimization': require('../assets/images/tool-icons-v2/22 - Mobile Optimization.webp'),
  '22-nft-music': require('../assets/images/tool-icons-v2/22--nft-music.webp'),
  '22-promotions': require('../assets/images/tool-icons-v2/22-promotions.webp'),
  '22-wifi': require('../assets/images/tool-icons-v2/22-wifi.webp'),
  '22periscope': require('../assets/images/tool-icons-v2/22_Periscope.webp'),
  '23': require('../assets/images/tool-icons-v2/23.webp'),
  '23-a': require('../assets/images/tool-icons-v2/23 a.webp'),
  '23-domain': require('../assets/images/tool-icons-v2/23 Domain.webp'),
  '23-low-life-punk': require('../assets/images/tool-icons-v2/23 Low-Life (Punk).webp'),
  '23-nft-games': require('../assets/images/tool-icons-v2/23--nft-games.webp'),
  '23-traditional-marketing': require('../assets/images/tool-icons-v2/23-traditional-marketing.webp'),
  '23-virtual-reality': require('../assets/images/tool-icons-v2/23-virtual-reality.webp'),
  '23figma': require('../assets/images/tool-icons-v2/23_Figma.webp'),
  '24': require('../assets/images/tool-icons-v2/24.webp'),
  '24-a': require('../assets/images/tool-icons-v2/24 a.webp'),
  '24-antivirus': require('../assets/images/tool-icons-v2/24 Antivirus.webp'),
  '24-body-modification': require('../assets/images/tool-icons-v2/24 Body Modification.webp'),
  '24-cloud': require('../assets/images/tool-icons-v2/24-cloud.webp'),
  '24-internet-marketing': require('../assets/images/tool-icons-v2/24-internet-marketing.webp'),
  '24-nft-fashion': require('../assets/images/tool-icons-v2/24--nft-fashion.webp'),
  '24telegram': require('../assets/images/tool-icons-v2/24_Telegram.webp'),
  '25': require('../assets/images/tool-icons-v2/25.webp'),
  '25-a': require('../assets/images/tool-icons-v2/25 a.webp'),
  '25-blockchain': require('../assets/images/tool-icons-v2/25-blockchain.webp'),
  '25-encryption': require('../assets/images/tool-icons-v2/25 Encryption.webp'),
  '25-marketing-campaign': require('../assets/images/tool-icons-v2/25-marketing-campaign.webp'),
  '25-nft-memes': require('../assets/images/tool-icons-v2/25--nft-memes.webp'),
  '25-target': require('../assets/images/tool-icons-v2/25 Target.webp'),
  '25medium': require('../assets/images/tool-icons-v2/25_Medium.webp'),
  '26': require('../assets/images/tool-icons-v2/26.webp'),
  '26-augmented-reality': require('../assets/images/tool-icons-v2/26 Augmented Reality.webp'),
  '26-conversion-rate': require('../assets/images/tool-icons-v2/26-conversion-rate.webp'),
  '26-hologram': require('../assets/images/tool-icons-v2/26-hologram.webp'),
  '26-nft-gallery': require('../assets/images/tool-icons-v2/26-nft-gallery.webp'),
  '26-password': require('../assets/images/tool-icons-v2/26 Password.webp'),
  '26messenger': require('../assets/images/tool-icons-v2/26_Messenger.webp'),
  '27': require('../assets/images/tool-icons-v2/27.webp'),
  '27-5g': require('../assets/images/tool-icons-v2/27-5g.webp'),
  '27-advertisement': require('../assets/images/tool-icons-v2/27-advertisement.webp'),
  '27-cyber-eye': require('../assets/images/tool-icons-v2/27 Cyber Eye.webp'),
  '27-digital-asset': require('../assets/images/tool-icons-v2/27--digital-asset.webp'),
  '27-ip-address': require('../assets/images/tool-icons-v2/27 IP Address.webp'),
  '27github': require('../assets/images/tool-icons-v2/27_GitHub.webp'),
  '28': require('../assets/images/tool-icons-v2/28.webp'),
  '28-flash-drive': require('../assets/images/tool-icons-v2/28 Flash Drive.webp'),
  '28-nft-buy': require('../assets/images/tool-icons-v2/28--nft-buy.webp'),
  '28-on-page-seo': require('../assets/images/tool-icons-v2/28-on-page-seo.webp'),
  '28-rootkit': require('../assets/images/tool-icons-v2/28 Rootkit.webp'),
  '28-server': require('../assets/images/tool-icons-v2/28-server.webp'),
  '28tinder': require('../assets/images/tool-icons-v2/28_Tinder.webp'),
  '29': require('../assets/images/tool-icons-v2/29.webp'),
  '29-biometric': require('../assets/images/tool-icons-v2/29-biometric.webp'),
  '29-nft-sell': require('../assets/images/tool-icons-v2/29--nft-sell.webp'),
  '29-off-page-seo': require('../assets/images/tool-icons-v2/29-off-page-seo.webp'),
  '29-spyware': require('../assets/images/tool-icons-v2/29 Spyware.webp'),
  '29-weapon': require('../assets/images/tool-icons-v2/29 Weapon.webp'),
  '29twitch': require('../assets/images/tool-icons-v2/29_Twitch.webp'),
  '3-a': require('../assets/images/tool-icons-v2/3 a.webp'),
  '3-blockchain': require('../assets/images/tool-icons-v2/3-blockchain.webp'),
  '3-cyberthreat': require('../assets/images/tool-icons-v2/3 Cyberthreat.webp'),
  '3-dystopia': require('../assets/images/tool-icons-v2/3 Dystopia.webp'),
  '3-industry': require('../assets/images/tool-icons-v2/3-industry.webp'),
  '3-online-payment': require('../assets/images/tool-icons-v2/3-online-payment.webp'),
  '3-presentation': require('../assets/images/tool-icons-v2/3 - Presentation.webp'),
  '3-tablet': require('../assets/images/tool-icons-v2/3. Tablet.webp'),
  '3-trolley': require('../assets/images/tool-icons-v2/3. Trolley.webp'),
  '3-web-check': require('../assets/images/tool-icons-v2/3. Web Check.webp'),
  '3-website-traffic': require('../assets/images/tool-icons-v2/3-website-traffic.webp'),
  '30': require('../assets/images/tool-icons-v2/30.webp'),
  '30-nft-exchange': require('../assets/images/tool-icons-v2/30--nft-exchange.webp'),
  '30-satelite': require('../assets/images/tool-icons-v2/30-satelite.webp'),
  '30-social-engineering': require('../assets/images/tool-icons-v2/30 Social Engineering.webp'),
  '30-technical-seo': require('../assets/images/tool-icons-v2/30-technical-seo.webp'),
  '30-techwear': require('../assets/images/tool-icons-v2/30 Techwear.webp'),
  '30slack': require('../assets/images/tool-icons-v2/30_Slack.webp'),
  '4-a': require('../assets/images/tool-icons-v2/4 a.webp'),
  '4-alpha': require('../assets/images/tool-icons-v2/4-alpha.webp'),
  '4-call-center': require('../assets/images/tool-icons-v2/4-call-center.webp'),
  '4-camera': require('../assets/images/tool-icons-v2/4. Camera.webp'),
  '4-hardware-security': require('../assets/images/tool-icons-v2/4 Hardware Security.webp'),
  '4-keyword-researchb': require('../assets/images/tool-icons-v2/4. Keyword Researchb.webp'),
  '4-knowledge': require('../assets/images/tool-icons-v2/4-knowledge.webp'),
  '4-packagin': require('../assets/images/tool-icons-v2/4. Packagin.webp'),
  '4-promotion': require('../assets/images/tool-icons-v2/4 - Promotion.webp'),
  '4-search-engine': require('../assets/images/tool-icons-v2/4-search-engine.webp'),
  '4-societal-collapse': require('../assets/images/tool-icons-v2/4 Societal Collapse.webp'),
  '5-a': require('../assets/images/tool-icons-v2/5 a.webp'),
  '5-airdrop': require('../assets/images/tool-icons-v2/5-airdrop.webp'),
  '5-artificial-intelligence': require('../assets/images/tool-icons-v2/5 Artificial Intelligence.webp'),
  '5-engineering': require('../assets/images/tool-icons-v2/5-engineering.webp'),
  '5-internet-security': require('../assets/images/tool-icons-v2/5 - Internet Security.webp'),
  '5-keyword': require('../assets/images/tool-icons-v2/5-keyword.webp'),
  '5-online-training': require('../assets/images/tool-icons-v2/5-online-training.webp'),
  '5-software-security': require('../assets/images/tool-icons-v2/5 Software Security.webp'),
  '5-truck': require('../assets/images/tool-icons-v2/5. Truck.webp'),
  '5-user-targeting2': require('../assets/images/tool-icons-v2/5. User Targeting2.webp'),
  '5-video-camera': require('../assets/images/tool-icons-v2/5. Video Camera.webp'),
  '6-a': require('../assets/images/tool-icons-v2/6 a.webp'),
  '6-automation': require('../assets/images/tool-icons-v2/6-automation.webp'),
  '6-bot': require('../assets/images/tool-icons-v2/6--bot.webp'),
  '6-cloud-security': require('../assets/images/tool-icons-v2/6 Cloud Security.webp'),
  '6-email-notification': require('../assets/images/tool-icons-v2/6-email-notification.webp'),
  '6-implant': require('../assets/images/tool-icons-v2/6 Implant.webp'),
  '6-marketing-strategy': require('../assets/images/tool-icons-v2/6 - Marketing Strategy.webp'),
  '6-microphone': require('../assets/images/tool-icons-v2/6. Microphone.webp'),
  '6-online-ads2': require('../assets/images/tool-icons-v2/6. Online Ads2.webp'),
  '6-search-volume': require('../assets/images/tool-icons-v2/6-search-volume.webp'),
  '6-store': require('../assets/images/tool-icons-v2/6. Store.webp'),
  '7-a': require('../assets/images/tool-icons-v2/7 a.webp'),
  '7-computer': require('../assets/images/tool-icons-v2/7-computer.webp'),
  '7-copywriting': require('../assets/images/tool-icons-v2/7-copywriting.webp'),
  '7-coupon': require('../assets/images/tool-icons-v2/7. Coupon.webp'),
  '7-developer-male': require('../assets/images/tool-icons-v2/7--developer-male.webp'),
  '7-hashtag': require('../assets/images/tool-icons-v2/7 - Hashtag.webp'),
  '7-headphones': require('../assets/images/tool-icons-v2/7. Headphones.webp'),
  '7-marketing-budget': require('../assets/images/tool-icons-v2/7. Marketing Budget.webp'),
  '7-microchip': require('../assets/images/tool-icons-v2/7 Microchip.webp'),
  '7-network-security': require('../assets/images/tool-icons-v2/7 Network Security.webp'),
  '7-product-and-trolley': require('../assets/images/tool-icons-v2/7-product-and-trolley.webp'),
  '8-a': require('../assets/images/tool-icons-v2/8 a.webp'),
  '8-ads': require('../assets/images/tool-icons-v2/8-ads.webp'),
  '8-cloud-transfer': require('../assets/images/tool-icons-v2/8 - Cloud Transfer.webp'),
  '8-developer-female': require('../assets/images/tool-icons-v2/8--developer-female.webp'),
  '8-discount': require('../assets/images/tool-icons-v2/8. Discount.webp'),
  '8-hologram': require('../assets/images/tool-icons-v2/8 Hologram.webp'),
  '8-market-launch': require('../assets/images/tool-icons-v2/8. Market Launch.webp'),
  '8-mobile-security': require('../assets/images/tool-icons-v2/8 Mobile Security.webp'),
  '8-optimized-content': require('../assets/images/tool-icons-v2/8-optimized-content.webp'),
  '8-smartphone': require('../assets/images/tool-icons-v2/8-smartphone.webp'),
  '8b': require('../assets/images/tool-icons-v2/8b.webp'),
  '9-404-error': require('../assets/images/tool-icons-v2/9 - 404 Error.webp'),
  '9-a': require('../assets/images/tool-icons-v2/9 a.webp'),
  '9-algorithm': require('../assets/images/tool-icons-v2/9-algorithm.webp'),
  '9-annoucement': require('../assets/images/tool-icons-v2/9. Annoucement.webp'),
  '9-digital-artist-male': require('../assets/images/tool-icons-v2/9-digital-artist-male.webp'),
  '9-endpoint-security': require('../assets/images/tool-icons-v2/9 Endpoint Security.webp'),
  '9-growth-chart': require('../assets/images/tool-icons-v2/9-growth-chart.webp'),
  '9-keyboard': require('../assets/images/tool-icons-v2/9. Keyboard.webp'),
  '9-neon-sign': require('../assets/images/tool-icons-v2/9 Neon Sign.webp'),
  '9-robot-arm': require('../assets/images/tool-icons-v2/9-robot-arm.webp'),
  '9-video-ads': require('../assets/images/tool-icons-v2/9. Video Ads.webp'),
  '9b': require('../assets/images/tool-icons-v2/9b.webp'),
  'abstract-10': require('../assets/images/tool-icons-v2/abstract-10.webp'),
  'abstract-11': require('../assets/images/tool-icons-v2/abstract-11.webp'),
  'abstract-14': require('../assets/images/tool-icons-v2/abstract-14.webp'),
  'abstract-15': require('../assets/images/tool-icons-v2/abstract-15.webp'),
  'abstract-18': require('../assets/images/tool-icons-v2/abstract-18.webp'),
  'abstract-19': require('../assets/images/tool-icons-v2/abstract-19.webp'),
  'abstract-2': require('../assets/images/tool-icons-v2/abstract-2.webp'),
  'abstract-20': require('../assets/images/tool-icons-v2/abstract-20.webp'),
  'abstract-3': require('../assets/images/tool-icons-v2/abstract-3.webp'),
  'abstract-4': require('../assets/images/tool-icons-v2/abstract-4.webp'),
  'abstract-5': require('../assets/images/tool-icons-v2/abstract-5.webp'),
  'abstract-6': require('../assets/images/tool-icons-v2/abstract-6.webp'),
  'abstract-7': require('../assets/images/tool-icons-v2/abstract-7.webp'),
  'abstract-8': require('../assets/images/tool-icons-v2/abstract-8.webp'),
  'abstract-9': require('../assets/images/tool-icons-v2/abstract-9.webp'),
  'account': require('../assets/images/tool-icons-v2/Account.webp'),
  'add-to-basket': require('../assets/images/tool-icons-v2/add-to-basket.webp'),
  'ai-biometric-eye': require('../assets/images/tool-icons-v2/ai biometric eye.webp'),
  'ai-book': require('../assets/images/tool-icons-v2/ai book.webp'),
  'ai-brain': require('../assets/images/tool-icons-v2/ai brain.webp'),
  'ai-chip': require('../assets/images/tool-icons-v2/ai chip.webp'),
  'ai-customer-service': require('../assets/images/tool-icons-v2/AI Customer Service.webp'),
  'ai-fingerprint-authentication': require('../assets/images/tool-icons-v2/ai fingerprint authentication.webp'),
  'ai-generator': require('../assets/images/tool-icons-v2/ai generator.webp'),
  'ai-idea': require('../assets/images/tool-icons-v2/ai idea.webp'),
  'ai-image-generator': require('../assets/images/tool-icons-v2/ai image generator.webp'),
  'ai-in-hand': require('../assets/images/tool-icons-v2/ai in hand.webp'),
  'ai-industrial-arm': require('../assets/images/tool-icons-v2/ai industrial arm.webp'),
  'ai-interaction': require('../assets/images/tool-icons-v2/AI Interaction.webp'),
  'ai-learning': require('../assets/images/tool-icons-v2/AI Learning.webp'),
  'ai-operator': require('../assets/images/tool-icons-v2/AI Operator.webp'),
  'ai-proggamming': require('../assets/images/tool-icons-v2/ai proggamming.webp'),
  'ai-robotic-hand': require('../assets/images/tool-icons-v2/ai robotic hand.webp'),
  'ai-scanner': require('../assets/images/tool-icons-v2/ai scanner.webp'),
  'ai-server': require('../assets/images/tool-icons-v2/ai server.webp'),
  'ai-smartphone': require('../assets/images/tool-icons-v2/ai smartphone.webp'),
  'alarm': require('../assets/images/tool-icons-v2/alarm.webp'),
  'atm': require('../assets/images/tool-icons-v2/atm.webp'),
  'automation-testing': require('../assets/images/tool-icons-v2/Automation Testing.webp'),
  'badge-discount': require('../assets/images/tool-icons-v2/Badge discount.webp'),
  'basket-promo': require('../assets/images/tool-icons-v2/Basket Promo.webp'),
  'bonus-gift': require('../assets/images/tool-icons-v2/Bonus gift.webp'),
  'bot': require('../assets/images/tool-icons-v2/bot.webp'),
  'brain': require('../assets/images/tool-icons-v2/Brain.webp'),
  'brain-chip': require('../assets/images/tool-icons-v2/Brain Chip.webp'),
  'buy-now': require('../assets/images/tool-icons-v2/Buy Now.webp'),
  'buy-package': require('../assets/images/tool-icons-v2/buy-package.webp'),
  'buyer-reviews': require('../assets/images/tool-icons-v2/buyer-reviews.webp'),
  'calendar': require('../assets/images/tool-icons-v2/calendar.webp'),
  'calendar-discount': require('../assets/images/tool-icons-v2/Calendar discount.webp'),
  'camera': require('../assets/images/tool-icons-v2/camera.webp'),
  'card': require('../assets/images/tool-icons-v2/card.webp'),
  'cash': require('../assets/images/tool-icons-v2/Cash.webp'),
  'chat': require('../assets/images/tool-icons-v2/chat.webp'),
  'chatbot': require('../assets/images/tool-icons-v2/Chatbot.webp'),
  'checkout': require('../assets/images/tool-icons-v2/Checkout.webp'),
  'chip-in-ai-robotic-hand': require('../assets/images/tool-icons-v2/chip in ai robotic hand.webp'),
  'clock': require('../assets/images/tool-icons-v2/clock.webp'),
  'cloud': require('../assets/images/tool-icons-v2/cloud.webp'),
  'compas': require('../assets/images/tool-icons-v2/compas.webp'),
  'contact': require('../assets/images/tool-icons-v2/contact.webp'),
  'conversion-rate': require('../assets/images/tool-icons-v2/conversion-rate.webp'),
  'credit-card': require('../assets/images/tool-icons-v2/Credit Card.webp'),
  'credit-card-sale': require('../assets/images/tool-icons-v2/Credit Card Sale.webp'),
  'customer-support': require('../assets/images/tool-icons-v2/Customer Support.webp'),
  'data-filtering': require('../assets/images/tool-icons-v2/Data Filtering.webp'),
  'data-learning': require('../assets/images/tool-icons-v2/Data Learning.webp'),
  'data-protection': require('../assets/images/tool-icons-v2/Data Protection.webp'),
  'data-sorting': require('../assets/images/tool-icons-v2/Data Sorting.webp'),
  'decision': require('../assets/images/tool-icons-v2/Decision.webp'),
  'desktop-discount': require('../assets/images/tool-icons-v2/Desktop Discount.webp'),
  'desktop-shop': require('../assets/images/tool-icons-v2/Desktop Shop.webp'),
  'discount': require('../assets/images/tool-icons-v2/Discount.webp'),
  'discount-by-phone': require('../assets/images/tool-icons-v2/Discount by phone.webp'),
  'discount-gift': require('../assets/images/tool-icons-v2/Discount gift.webp'),
  'discount-voucher': require('../assets/images/tool-icons-v2/discount-voucher.webp'),
  'drive': require('../assets/images/tool-icons-v2/drive.webp'),
  'ecommerce': require('../assets/images/tool-icons-v2/eCommerce.webp'),
  'ecommerce-app': require('../assets/images/tool-icons-v2/ecommerce-app.webp'),
  'extra-gift': require('../assets/images/tool-icons-v2/Extra gift.webp'),
  'eye-scanner': require('../assets/images/tool-icons-v2/Eye Scanner.webp'),
  'facebook': require('../assets/images/tool-icons-v2/facebook.webp'),
  'fast-delivery': require('../assets/images/tool-icons-v2/Fast Delivery.webp'),
  'favorite-package': require('../assets/images/tool-icons-v2/favorite-package.webp'),
  'ff-logo': require('../assets/images/tool-icons-v2/FF Logo.webp'),
  'file-manager': require('../assets/images/tool-icons-v2/File manager.webp'),
  'film': require('../assets/images/tool-icons-v2/film.webp'),
  'flash-sale': require('../assets/images/tool-icons-v2/Flash sale.webp'),
  'flickr': require('../assets/images/tool-icons-v2/flickr.webp'),
  'free-delivery': require('../assets/images/tool-icons-v2/Free Delivery.webp'),
  'gallery': require('../assets/images/tool-icons-v2/gallery.webp'),
  'game': require('../assets/images/tool-icons-v2/game.webp'),
  'geographic-based-discount': require('../assets/images/tool-icons-v2/Geographic-based discount.webp'),
  'gift-boxes': require('../assets/images/tool-icons-v2/Gift boxes.webp'),
  'gift-card': require('../assets/images/tool-icons-v2/Gift Card.webp'),
  'gift-coupon': require('../assets/images/tool-icons-v2/Gift coupon.webp'),
  'hosting-drive': require('../assets/images/tool-icons-v2/hosting-drive.webp'),
  'hostingdrive': require('../assets/images/tool-icons-v2/Hosting_Drive.webp'),
  'humanoid-robotic': require('../assets/images/tool-icons-v2/Humanoid Robotic.webp'),
  'instagram': require('../assets/images/tool-icons-v2/instagram.webp'),
  'kuaishou': require('../assets/images/tool-icons-v2/kuaishou.webp'),
  'linkedin': require('../assets/images/tool-icons-v2/linkedin.webp'),
  'list-and-trolley': require('../assets/images/tool-icons-v2/list-and-trolley.webp'),
  'loyalty-program': require('../assets/images/tool-icons-v2/Loyalty Program.webp'),
  'mail-discount': require('../assets/images/tool-icons-v2/Mail Discount.webp'),
  'media-player': require('../assets/images/tool-icons-v2/Media player.webp'),
  'medium': require('../assets/images/tool-icons-v2/medium.webp'),
  'messenger': require('../assets/images/tool-icons-v2/messenger.webp'),
  'meta': require('../assets/images/tool-icons-v2/meta.webp'),
  'midnight-sale': require('../assets/images/tool-icons-v2/Midnight sale.webp'),
  'mobile-shopping': require('../assets/images/tool-icons-v2/mobile-shopping.webp'),
  'music': require('../assets/images/tool-icons-v2/music.webp'),
  'neural-network': require('../assets/images/tool-icons-v2/Neural Network.webp'),
  'neuralink': require('../assets/images/tool-icons-v2/Neuralink.webp'),
  'new': require('../assets/images/tool-icons-v2/New.webp'),
  'note': require('../assets/images/tool-icons-v2/note.webp'),
  'notification-promo': require('../assets/images/tool-icons-v2/Notification promo.webp'),
  'online-business': require('../assets/images/tool-icons-v2/online-business.webp'),
  'online-payment': require('../assets/images/tool-icons-v2/online-payment.webp'),
  'online-promotion': require('../assets/images/tool-icons-v2/online-promotion.webp'),
  'online-shopping': require('../assets/images/tool-icons-v2/online-shopping.webp'),
  'open-shop': require('../assets/images/tool-icons-v2/open-shop.webp'),
  'package': require('../assets/images/tool-icons-v2/package.webp'),
  'package-discount': require('../assets/images/tool-icons-v2/package-discount.webp'),
  'package-tracking': require('../assets/images/tool-icons-v2/Package Tracking.webp'),
  'packages': require('../assets/images/tool-icons-v2/Packages.webp'),
  'padlock': require('../assets/images/tool-icons-v2/padlock.webp'),
  'payment': require('../assets/images/tool-icons-v2/Payment.webp'),
  'payment-protected': require('../assets/images/tool-icons-v2/payment-protected.webp'),
  'payment-terminal-discount': require('../assets/images/tool-icons-v2/Payment terminal discount.webp'),
  'phone-shop': require('../assets/images/tool-icons-v2/Phone shop.webp'),
  'phonepayment': require('../assets/images/tool-icons-v2/Phone_Payment.webp'),
  'pinterest': require('../assets/images/tool-icons-v2/pinterest.webp'),
  'price-cut': require('../assets/images/tool-icons-v2/Price Cut.webp'),
  'price-tag': require('../assets/images/tool-icons-v2/Price Tag.webp'),
  'product-trolley': require('../assets/images/tool-icons-v2/product-trolley.webp'),
  'promo-boom': require('../assets/images/tool-icons-v2/Promo boom.webp'),
  'promotion': require('../assets/images/tool-icons-v2/Promotion.webp'),
  'rating': require('../assets/images/tool-icons-v2/Rating.webp'),
  'receipt': require('../assets/images/tool-icons-v2/Receipt.webp'),
  'recommended': require('../assets/images/tool-icons-v2/Recommended.webp'),
  'reddit': require('../assets/images/tool-icons-v2/reddit.webp'),
  'replace-product': require('../assets/images/tool-icons-v2/Replace Product.webp'),
  'return-product': require('../assets/images/tool-icons-v2/Return Product.webp'),
  'review': require('../assets/images/tool-icons-v2/Review.webp'),
  'robot': require('../assets/images/tool-icons-v2/Robot.webp'),
  'robotic-hand': require('../assets/images/tool-icons-v2/Robotic Hand.webp'),
  'sale': require('../assets/images/tool-icons-v2/Sale.webp'),
  'sales-analytics': require('../assets/images/tool-icons-v2/Sales Analytics.webp'),
  'save-more-money': require('../assets/images/tool-icons-v2/Save more money.webp'),
  'screen': require('../assets/images/tool-icons-v2/screen.webp'),
  'search-engine': require('../assets/images/tool-icons-v2/search-engine.webp'),
  'search-volume': require('../assets/images/tool-icons-v2/search-volume.webp'),
  'sem': require('../assets/images/tool-icons-v2/sem.webp'),
  'server': require('../assets/images/tool-icons-v2/server.webp'),
  'serverhosting': require('../assets/images/tool-icons-v2/Server_Hosting.webp'),
  'servers': require('../assets/images/tool-icons-v2/servers.webp'),
  'setting': require('../assets/images/tool-icons-v2/setting.webp'),
  'shield': require('../assets/images/tool-icons-v2/shield.webp'),
  'shop-gift': require('../assets/images/tool-icons-v2/Shop gift.webp'),
  'shop-more': require('../assets/images/tool-icons-v2/Shop more.webp'),
  'shopping-bag': require('../assets/images/tool-icons-v2/Shopping Bag.webp'),
  'shopping-basket': require('../assets/images/tool-icons-v2/shopping-basket.webp'),
  'shopping-cart': require('../assets/images/tool-icons-v2/Shopping Cart.webp'),
  'shopping-chat': require('../assets/images/tool-icons-v2/shopping-chat.webp'),
  'shopping-list': require('../assets/images/tool-icons-v2/Shopping List.webp'),
  'shopping-plus-one': require('../assets/images/tool-icons-v2/Shopping plus one.webp'),
  'snapchat': require('../assets/images/tool-icons-v2/snapchat.webp'),
  'sold-out': require('../assets/images/tool-icons-v2/Sold Out.webp'),
  'store-traffic': require('../assets/images/tool-icons-v2/Store Traffic.webp'),
  'telegram': require('../assets/images/tool-icons-v2/telegram.webp'),
  'text-scanning': require('../assets/images/tool-icons-v2/Text Scanning.webp'),
  'tiktok': require('../assets/images/tool-icons-v2/tiktok.webp'),
  'video-player': require('../assets/images/tool-icons-v2/video-player.webp'),
  'videoplayer': require('../assets/images/tool-icons-v2/Video_Player.webp'),
  'vine': require('../assets/images/tool-icons-v2/vine.webp'),
  'whatsapp': require('../assets/images/tool-icons-v2/whatsapp.webp'),
  'wishlist': require('../assets/images/tool-icons-v2/Wishlist.webp'),
  'worldwide-shipping': require('../assets/images/tool-icons-v2/Worldwide Shipping.webp'),
  'x-twitter': require('../assets/images/tool-icons-v2/x-twitter.webp'),
  'youtube': require('../assets/images/tool-icons-v2/youtube.webp'),
};

const DEFAULT_ICON = require('../assets/images/tool-icons-v2/19-marketing-strategy.webp');

export function getToolIcon(slug: string, category?: string): any {
  const normalized = slug.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  if (ToolIconImages[normalized]) return ToolIconImages[normalized];
  if (category) {
    const catKey = category.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    if (ToolIconImages[catKey]) return ToolIconImages[catKey];
  }
  // Fuzzy match: check if any part of the slug matches a key
  const parts = normalized.split("-").filter(p => p.length > 3);
  for (const key of Object.keys(ToolIconImages)) {
    if (parts.some(p => key.includes(p))) return ToolIconImages[key];
  }
  return DEFAULT_ICON;
}
