/**
 * withRNEdgeToEdgeFix.js
 *
 * Expo config plugin that wires the generated Android project to use
 * our patched react-android AAR (0.83.6-e2e.1) from the local-maven
 * directory committed to this repo (android-patches/local-maven/).
 *
 * The patched AAR fixes Android 15 deprecated edge-to-edge APIs in:
 *   - com.facebook.react.modules.statusbar.StatusBarModule
 *   - com.facebook.react.views.view.WindowUtil
 *
 * No secrets or tokens required — the AAR is committed to the repo.
 * Rebuild the AAR by triggering: .github/workflows/patch-react-android.yml
 */

const { withProjectBuildGradle, withSettingsGradle } = require('@expo/config-plugins');
const path = require('path');

const PATCHED_VERSION = '0.83.6-e2e.1';

// $rootDir in Gradle = <project-root>/android/ (generated by expo prebuild).
// The local-maven repo lives at <project-root>/android-patches/local-maven/.
// So the relative path from $rootDir is ../android-patches/local-maven.
const LOCAL_MAVEN_RELATIVE = '../android-patches/local-maven';

const MAVEN_BLOCK = `
        // ── Patched react-android: Android 15 edge-to-edge deprecated API fix ──
        maven { url new File(rootDir, "${LOCAL_MAVEN_RELATIVE}").toURI() }`;

// Injected into allprojects{} in root build.gradle so it applies to ALL subprojects,
// even those that declare their own repositories (which override settings.gradle repos).
const ALL_PROJECTS_BLOCK = `
allprojects {
    // ── Patched react-android: Android 15 edge-to-edge deprecated API fix ──
    repositories {
        maven { url new File(rootDir, "${LOCAL_MAVEN_RELATIVE}").toURI() }
    }
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-android:${PATCHED_VERSION}"
        }
    }
}`;

function insertLocalRepoBeforeMavenCentral(contents) {
  const dependencyIndex = contents.indexOf('dependencyResolutionManagement');
  const searchStart = dependencyIndex >= 0 ? dependencyIndex : 0;
  const mavenCentralIndex = contents.indexOf('mavenCentral()', searchStart);

  if (mavenCentralIndex < 0) {
    return contents;
  }

  return `${contents.slice(0, mavenCentralIndex)}${MAVEN_BLOCK}\n${contents.slice(mavenCentralIndex)}`;
}

module.exports = function withRNEdgeToEdgeFix(config) {
  // 1. Add local Maven repo to settings.gradle (covers projects that
  //    use dependencyResolutionManagement / don't declare their own repos)
  config = withSettingsGradle(config, (config) => {
    const contents = config.modResults.contents;
    if (contents.includes('Patched react-android')) return config;
    config.modResults.contents = insertLocalRepoBeforeMavenCentral(contents);
    return config;
  });

  // 2. Add allprojects{repositories+force} to root build.gradle — this is what
  //    actually works for subprojects that declare their own repositories, because
  //    those subprojects ignore dependencyResolutionManagement in settings.gradle.
  config = withProjectBuildGradle(config, (config) => {
    const contents = config.modResults.contents;
    if (contents.includes('Patched react-android')) return config;
    config.modResults.contents = `${contents.trimEnd()}\n${ALL_PROJECTS_BLOCK}\n`;
    return config;
  });

  return config;
};
