const fs = require('fs');
const path = require('path');
const {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
} = require('expo/config-plugins');

/**
 * Start Firebase from values compiled into BuildConfig, not from string
 * resources that Google Play can translate.
 *
 * Root cause this fixes (verified 2026-09-15 on the Play-generated APK for
 * vc 1056): Play Console's automatic app-string translation added `en` and
 * `fr` copies of the google-services strings to the APKs Play delivers.
 * `string/google_api_key` (en) and (fr) held a key deleted in April 2026, so on
 * every English phone FirebaseOptions.fromResource() picked the dead key and
 * every Firebase call (Installations, App Check, phone OTP) failed with
 * "API key expired". Sideloaded/EAS APKs had no `en` copy, so they worked.
 *
 * FirebaseInitProvider (initOrder 100) calls FirebaseApp.initializeApp(context),
 * which returns the existing default app when one is already registered. The
 * provider added here runs first (initOrder 101) and registers the default app
 * with FirebaseOptions built from BuildConfig, so the translatable resources are
 * never read. The same translation also rewrote `app_name` and
 * `expo_runtime_version`, so the manifest label and the expo-updates runtime
 * version are pinned to literal values here too.
 */

const PROVIDER_CLASS = 'LocaleProofFirebaseInitProvider';

function readGoogleServices(config, projectRoot) {
  const rel = config.android?.googleServicesFile;
  if (!rel) throw new Error('[withLocaleProofFirebaseOptions] android.googleServicesFile is not set');
  const doc = JSON.parse(fs.readFileSync(path.resolve(projectRoot, rel), 'utf8'));
  const pkg = config.android?.package;
  const client = (doc.client || []).find(
    (c) => c.client_info?.android_client_info?.package_name === pkg
  );
  if (!client) throw new Error(`[withLocaleProofFirebaseOptions] no client for ${pkg} in ${rel}`);
  return {
    FIREBASE_API_KEY: client.api_key?.[0]?.current_key,
    FIREBASE_APP_ID: client.client_info?.mobilesdk_app_id,
    FIREBASE_PROJECT_ID: doc.project_info?.project_id,
    FIREBASE_SENDER_ID: doc.project_info?.project_number,
    FIREBASE_STORAGE_BUCKET: doc.project_info?.storage_bucket || '',
    FIREBASE_DATABASE_URL: doc.project_info?.firebase_url || '',
  };
}

function providerSource(pkg) {
  return `package ${pkg}

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.net.Uri
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions

// Generated by plugins/withLocaleProofFirebaseOptions.js -- see that file for why.
class ${PROVIDER_CLASS} : ContentProvider() {
  override fun onCreate(): Boolean {
    val ctx = context?.applicationContext ?: return false
    if (FirebaseApp.getApps(ctx).none { it.name == FirebaseApp.DEFAULT_APP_NAME }) {
      val builder = FirebaseOptions.Builder()
        .setApiKey(BuildConfig.FIREBASE_API_KEY)
        .setApplicationId(BuildConfig.FIREBASE_APP_ID)
        .setProjectId(BuildConfig.FIREBASE_PROJECT_ID)
        .setGcmSenderId(BuildConfig.FIREBASE_SENDER_ID)
      if (BuildConfig.FIREBASE_STORAGE_BUCKET.isNotEmpty()) builder.setStorageBucket(BuildConfig.FIREBASE_STORAGE_BUCKET)
      if (BuildConfig.FIREBASE_DATABASE_URL.isNotEmpty()) builder.setDatabaseUrl(BuildConfig.FIREBASE_DATABASE_URL)
      FirebaseApp.initializeApp(ctx, builder.build())
    }
    return false
  }

  override fun query(uri: Uri, projection: Array<out String>?, selection: String?, selectionArgs: Array<out String>?, sortOrder: String?): Cursor? = null
  override fun getType(uri: Uri): String? = null
  override fun insert(uri: Uri, values: ContentValues?): Uri? = null
  override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0
  override fun update(uri: Uri, values: ContentValues?, selection: String?, selectionArgs: Array<out String>?): Int = 0
}
`;
}

module.exports = function withLocaleProofFirebaseOptions(config) {
  // 1. BuildConfig fields from google-services.json (values already ship in the APK).
  config = withAppBuildGradle(config, (config) => {
    const values = readGoogleServices(config, config.modRequest.projectRoot);
    for (const [name, value] of Object.entries(values)) {
      if (value === undefined) throw new Error(`[withLocaleProofFirebaseOptions] missing ${name}`);
    }
    const marker = '// withLocaleProofFirebaseOptions';
    let src = config.modResults.contents;
    src = src.replace(new RegExp(`\\n\\s*${marker}[\\s\\S]*?${marker} end\\n`), '\n');
    const fields = Object.entries(values)
      .map(([name, value]) => `        buildConfigField "String", "${name}", ${JSON.stringify(JSON.stringify(String(value)))}`)
      .join('\n');
    const block = `\n        ${marker}\n${fields}\n        ${marker} end\n`;
    if (!/defaultConfig\s*\{/.test(src)) {
      throw new Error('[withLocaleProofFirebaseOptions] defaultConfig block not found in app/build.gradle');
    }
    src = src.replace(/defaultConfig\s*\{/, (m) => m + block);

    // FirebaseApp/FirebaseOptions come from firebase-common, which
    // @react-native-firebase/app only declares as `implementation`, so the app
    // module cannot compile against it. Use the same BoM RN Firebase pins.
    const depMarker = '// withLocaleProofFirebaseOptions deps';
    src = src.replace(new RegExp(`\\n\\s*${depMarker}[\\s\\S]*?${depMarker} end\\n`), '\n');
    const bom = require(require.resolve('@react-native-firebase/app/package.json', {
      paths: [config.modRequest.projectRoot],
    })).sdkVersions.android.firebase;
    const deps = `\n    ${depMarker}\n    implementation platform("com.google.firebase:firebase-bom:${bom}")\n    implementation "com.google.firebase:firebase-common"\n    ${depMarker} end\n`;
    if (!/^dependencies\s*\{/m.test(src)) {
      throw new Error('[withLocaleProofFirebaseOptions] top-level dependencies block not found in app/build.gradle');
    }
    src = src.replace(/^dependencies\s*\{/m, (m) => m + deps);
    config.modResults.contents = src;
    return config;
  });

  // 2. The provider source file.
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const pkg = config.android?.package;
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java', ...pkg.split('.')
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${PROVIDER_CLASS}.kt`), providerSource(pkg));
      return config;
    },
  ]);

  // 3. Manifest: register the provider ahead of FirebaseInitProvider and pin
  //    the label and expo-updates runtime version to literals.
  config = withAndroidManifest(config, (config) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
    const pkg = config.android?.package;

    application.provider = (application.provider || []).filter(
      (p) => p.$?.['android:name'] !== `.${PROVIDER_CLASS}`
    );
    application.provider.push({
      $: {
        'android:name': `.${PROVIDER_CLASS}`,
        'android:authorities': `${pkg}.localeprooffirebaseinit`,
        'android:exported': 'false',
        'android:directBootAware': 'true',
        'android:initOrder': '101',
      },
    });

    if (config.name) application.$['android:label'] = config.name;

    const runtimeVersion = typeof config.runtimeVersion === 'string' ? config.runtimeVersion : config.version;
    for (const item of application['meta-data'] || []) {
      if (item.$?.['android:name'] === 'expo.modules.updates.EXPO_RUNTIME_VERSION' && runtimeVersion) {
        item.$['android:value'] = runtimeVersion;
      }
    }
    return config;
  });

  return config;
};
