import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { Colors, Gradients, Spacing, BorderRadius } from '../../constants/theme';
import AnimatedBackground from '../../components/common/AnimatedBackground';

const TermsScreen = () => {
  const navigation = useNavigation();

  return (
    <AnimatedBackground variant="profile" showParticles={false}>
      <LinearGradient colors={Gradients.dark} style={styles.header}>
        <View style={styles.headerContent}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
            <Feather name="arrow-left" size={24} color={Colors.white} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Terms of Use</Text>
          <View style={styles.placeholder} />
        </View>
      </LinearGradient>

      <ScrollView style={styles.content} contentContainerStyle={styles.contentContainer} showsVerticalScrollIndicator={false}>
        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Terms of Use</Text>
          <Text style={styles.lastUpdated}>Last Updated: March 1, 2026</Text>

          <Text style={styles.paragraph}>
            Welcome to MarketingTool ("the App"). By using this application, you agree to comply with and be bound by the following terms and conditions.
          </Text>

          <Text style={styles.heading}>Acceptance of Terms</Text>
          <Text style={styles.paragraph}>
            By accessing or using MarketingTool, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. If you do not agree, please do not use the App.
          </Text>

          <Text style={styles.heading}>Description of Service</Text>
          <Text style={styles.paragraph}>
            MarketingTool is an AI-powered marketing platform that provides tools for generating marketing content, managing ad campaigns, and analyzing marketing performance across multiple platforms including Google, Meta, and Shopify.
          </Text>

          <Text style={styles.heading}>User Accounts</Text>
          <Text style={styles.paragraph}>
            You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information during registration. You must notify us immediately of any unauthorized use of your account.
          </Text>

          <Text style={styles.heading}>Subscription & Billing</Text>
          <Text style={styles.paragraph}>
            Some features require a paid subscription. Subscription fees are billed in advance on a monthly or yearly basis. You may cancel your subscription at any time. Refunds are subject to our refund policy. Free trial users are limited to 3 AI generations per day.
          </Text>

          <Text style={styles.heading}>AI-Generated Content</Text>
          <Text style={styles.paragraph}>
            Content generated by MarketingTool's AI is provided as suggestions. You are solely responsible for reviewing, editing, and using any generated content. We do not guarantee the accuracy, completeness, or effectiveness of AI-generated content.
          </Text>

          <Text style={styles.heading}>Prohibited Uses</Text>
          <Text style={styles.paragraph}>
            You agree not to use the App to generate content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable. You may not attempt to reverse-engineer, decompile, or disassemble any part of the App.
          </Text>

          <Text style={styles.heading}>Intellectual Property</Text>
          <Text style={styles.paragraph}>
            All content, features, and functionality of the App are owned by AI MarketingTool LLC. Content you generate using the App belongs to you, subject to the underlying AI model's terms.
          </Text>

          <Text style={styles.heading}>Limitation of Liability</Text>
          <Text style={styles.paragraph}>
            MarketingTool is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App.
          </Text>

          <Text style={styles.heading}>Termination Policy</Text>
          <Text style={styles.paragraph}>
            We reserve the right to suspend or terminate your account in the event of any breach of these Terms. Such suspension or termination may occur without prior notice. Any suspected fraudulent, abusive, or illegal activity may be referred to appropriate law enforcement authorities.
          </Text>

          <Text style={styles.heading}>Governing Law</Text>
          <Text style={styles.paragraph}>
            These Terms shall be governed by and construed in accordance with the laws of the State of Wyoming, United States, without regard to its conflict of law provisions.
          </Text>

          <Text style={styles.heading}>Contact Information</Text>
          <Text style={styles.paragraph}>
            For any questions or concerns regarding these Terms of Use, please contact us at: help@marketingtool.pro
          </Text>

          <Text style={styles.companyInfo}>
            AI MarketingTool LLC{'\n'}
            30 N Gould St, STE R{'\n'}
            Sheridan, WY 82801, USA
          </Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerCompany}>AI MarketingTool LLC</Text>
          <Text style={styles.footerEmail}>help@marketingtool.pro</Text>
        </View>

        <View style={{ height: 100 }} />
      </ScrollView>
    </AnimatedBackground>
  );
};

const styles = StyleSheet.create({
  header: {
    paddingTop: 60,
    paddingBottom: Spacing.lg,
    paddingHorizontal: Spacing.lg,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.white,
  },
  placeholder: {
    width: 44,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: Spacing.lg,
  },
  card: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: Colors.white,
    marginBottom: 4,
  },
  lastUpdated: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginBottom: Spacing.lg,
  },
  heading: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.white,
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  paragraph: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  companyInfo: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 22,
    marginTop: Spacing.lg,
    fontWeight: '500',
  },
  footer: {
    alignItems: 'center',
    paddingTop: Spacing.xl,
  },
  footerCompany: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.secondary,
  },
  footerEmail: {
    fontSize: 13,
    color: Colors.textTertiary,
    marginTop: 4,
  },
});

export default TermsScreen;
