services:
  ci-server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env   # GITHUB_APP_IDENTIFIER, GITHUB_WEBHOOK_SECRET, GITHUB_PRIVATE_KEY, GITHUB_APP_USER_NAME, GITHUB_APP_USER_EMAIL
    restart: unless-stopped
