# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv', '~> 3.1'
gem 'git', '~> 2.3'
gem 'jwt', '~> 2.9'
gem 'octokit', '~> 9.2'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'
gem 'rubocop', '~> 1.66', require: false
gem 'sinatra', '~> 4.1'
