version: 2.1

orbs:
  maven: circleci/maven@1.4.2

workflows:
  maven_workflow:
    jobs:
      - maven/test:
          executor:
            name: cimg/openjdk:21.0.2 # Uses CircleCI's official verified OpenJDK 21 image
          app_src_directory: 'backend'
